#!/usr/bin/perl
#
# SPINLOCK - Advanced GNU/Linux networks in commercial and education sectors.
#
# Copyright 2008-2009 SPINLOCK d.o.o., http://www.spinlocksolutions.com/
#                     Davor Ocelic, docelic@spinlocksolutions.com
#
# http://www.spinlocksolutions.com/
# http://techpubs.spinlocksolutions.com/
#
# Released under GPL v3 or later.
#
#
# Very simple script for turning a preseed file into LDIF format. This
# script does not load question's template into LDIF, it uses the necessary
# info contained in the preseed file. So, it works but is pretty crude.
#
# ** IT CREATES OUT OF DATE TREE STRUCTURE, DON'T USE IT **
#
# The script is mostly obsolete in favor of cdebconf2ldif which
# does everything the way you'd want it.
#
# preseed2ldif < preseed-file.txt
#

use warnings;
use strict;

my $domain= $ARGV[0] || 'dc=spinlock,dc=hr';

while( <STDIN>){
	chomp;

	next if /^#/;
	next if /^\s*$/;
	do{ warn "nomatch: $_\n"; next} unless /^(\S+)\s+(\S+)\s+(\S+)\s*(.*)$/;

	my( $owners, $item, $type, $value)= ($1, $2, $3, $4);

	print <<__EOP__;
dn: cn=$item,cn=_defaults_,ou=templates,$domain
objectClass: top
objectClass: debConfDbEntry
cn: $item
type: $type
owners: $owners

dn: cn=$item,cn=_defaults_,ou=hosts,$domain
objectClass: top
objectClass: debConfDbEntry
cn: $item
template: $item
owners: $owners
value: $value
flags: preseed

__EOP__
}

